version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - "5001:5000"
    networks:
      - microservices-net

  orders:
    build: ./orders
    ports:
      - "5002:5000"
    networks:
      - microservices-net

  payments:
    build: ./payments
    ports:
      - "5003:5000"
    networks:
      - microservices-net

  delivery:
    build: ./delivery
    ports:
      - "5004:5000"
    networks:
      - microservices-net

  user:
    build: ./user
    ports:
      - "5005:5000"
    networks:
      - microservices-net

  reviews:
    build: ./reviews
    ports:
      - "5006:5000"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

